export const weatherData = {
  data: {
    TZ_Data: "America/Port_of_Spain",
    abs_humidity: null,
    atmo_opacity: "Sunny",
    id: 3009,
    local_uv_irradiance_index: "Moderate",
    ls: 65,
    max_gts_temp: -6,
    max_temp: -25,
    min_gts_temp: -79,
    min_temp: -78,
    pressure: 868,
    pressure_string: "Higher",
    season: "Month 3",
    sol: 1314,
    status: 200,
    sunrise: "06:03",
    sunset: "17:47",
    terrestrial_date: "2021-06-30T00:00:00.000Z",
    unitOfMeasure: "Celsius",
    wind_direction: null,
    wind_speed: null,
  },
};
